### ISSUE TITLE
SUMO --version

### ISSUE THREAD

**Issue by a1wj1** [DaRL-LibSignal/LibSignal#11]
What is the version of SUMO

**Comment by derekmei233** [comment]
Hi a1wj1,
I believe the sumo version is dependent on the time you build your libsgnal library, since we are compatible with the latest sumo version. If you are specifically interested in the SUMO version you are currently using, please try this 
import sumolib
sumolib.version.gitDescribe()
This will give the version you are currently using. The version in our tutorial branch is v1_18.0
Hope this could be helpful.
